#
#  Be sure to run `pod spec lint CloseChannel.podspec' to ensure this is a
#  valid spec and to remove all comments including this before submitting the spec.
#
#  To learn more about Podspec attributes see https://guides.cocoapods.org/syntax/podspec.html
#  To see working Podspecs in the CocoaPods repo see https://github.com/CocoaPods/Specs/
#

# *** DO NOT EDIT THIS FILE BUT THE TEMPLATE IN THE CLOSE-IOS-SDK-SPM REPO INSTEAD ***

Pod::Spec.new do |spec|
  spec.name         = "CloseChannel"
  spec.version      = "2.0.0-beta1"
  spec.swift_versions = "5.0"
  spec.summary      = "The Mobile Close Channel SDK allows you to integrate the Close communication platform in your own iOS app."

  # This description is used to generate tags and improve search results.
  #   * Think: What does it do? Why did you write it? What is the focus?
  #   * Try to keep it short, snappy and to the point.
  #   * Write the description between the DESC delimiters below.
  #   * Finally, don't worry about the indent, CocoaPods strips it!
  spec.description  = <<-DESC
  The Close Mobile Channel SDK allows you to integrate the Close communication platform in your own iOS app. Stay relevant by reaching your customers with hyper-personalised messages
                   DESC

  spec.homepage     = "https://github.com/close-dev-team/mobile-close-channel-sdk-documentation-ios"
  spec.license      = { :type => "Proprietary", :file => "LICENSE" }
  spec.author             = { "Maurice de Bijl" => "maurice@thecloseapp.com" }

  # ――― Platform Specifics ――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  Keep in sync with IPHONEOS_DEPLOYMENT_TARGET of the CloseChannelSdk target.
  #

  spec.platform     = :ios, "15.0"


  # ――― Source Location ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  Specify the location from where the source should be retrieved.
  #  Supports git, hg, bzr, svn and HTTP.
  #

  spec.source       = { :git => "https://github.com/close-dev-team/mobile-close-channel-sdk-binary-ios.git", :tag => "#{spec.version}" }

  # Both are required: CloseChannel.framework has a hard @rpath link to
  # CloseChannelDependencies.framework, so vendoring CloseChannel alone fails at launch.
  # Swift Package Manager users never see this xcframework — they add the dependencies
  # package as a second package URL and SPM builds the umbrella from source instead.
  spec.vendored_frameworks = ['CloseChannel.xcframework', 'CloseChannelDependencies.xcframework']

  # These pods are needed so the consumer's Swift compiler can resolve
  # `import CryptoSwift` etc. that leak through CloseChannel's swiftinterface.
  # Actual symbols are provided by CloseChannelDependencies.xcframework at runtime.
  #
  # Keep in sync with the dependencies of mobile-close-channel-sdk-ios-dependencies,
  # plus SwiftyRSA, which sits outside that umbrella. Starscream is deliberately absent:
  # it arrives transitively through Socket.IO-Client-Swift.
  # SwiftyRSA stays on ~>1.7 because 1.8 was never pushed to the CocoaPods trunk.
  spec.dependency 'Socket.IO-Client-Swift', '~>16.1'
  spec.dependency 'CryptoSwift', '~>1.8.4'
  spec.dependency 'SwiftySound', '~>1.3'
  spec.dependency 'SQLite.swift', '0.15.3'
  spec.dependency 'SnapKit', '~>5.7'
  spec.dependency 'Device', '~>3.7'
  spec.dependency 'Fuzi', '~>3.1'
  spec.dependency 'SwiftyRSA', '~>1.7'

end
